TOP = ../..

ifdef EPICS_HOST_ARCH

include $(TOP)/configure/CONFIG
                                                                                
#DIRS += symbol
DIRS += edl
                                                                                
include $(TOP)/configure/RULES_DIRS

else

endif
