TOP=../..

include $(TOP)/configure/CONFIG

# -------------------------------
# Build an Diamond Support Module
# -------------------------------

# enzLoCuM4Readback.dbd will be installed into <top>/dbd
DBD += enzLoCuM4Readback.dbd

# enzLoCuM4Readback.dbd will be created from these files
enzLoCuM4Readback_DBD += base.dbd
enzLoCuM4Readback_DBD += Hy8401ip.dbd

include $(TOP)/configure/RULES
